# Generated by Django 3.2.4 on 2021-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='additional_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('data', models.IntegerField()),
                ('points', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('image', models.ImageField(default='', upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='legal_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=1000)),
                ('icon', models.ImageField(default='', upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='new_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('password1', models.IntegerField()),
                ('password2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quote_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('quary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=1000)),
                ('icon', models.ImageField(default='', upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='tax_compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('qurey', models.CharField(max_length=100)),
            ],
        ),
    ]
