# Generated by Django 3.2.4 on 2021-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bloging_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_services',
            name='data',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='additional_services',
            name='points',
            field=models.CharField(max_length=10000),
        ),
    ]
